// Portafolio. Cada proyecto genera /projects/<slug>/ (case study).
// Para agregar uno nuevo: copia un bloque, cambia los datos y pon sus
// imágenes en assets/img/work/. Luego: node scripts/build.mjs
//
// categories usa estas claves: websites, menus, catalogs, ecommerce, branding, systems, apps

export const categories = [
  { key: 'websites', label: 'Sitios web' },
  { key: 'menus', label: 'Menús' },
  { key: 'catalogs', label: 'Catálogos' },
  { key: 'ecommerce', label: 'E-commerce' },
  { key: 'branding', label: 'Branding' },
  { key: 'systems', label: 'Sistemas' },
  { key: 'apps', label: 'Apps' },
];

export const projects = [
  {
    slug: 's91-house-grill',
    kind: 'client',
    meta: 'Menú digital / Comida',
    web: null,
    chapters: [
      { t: 'Marca', d: 'El logo con la llama, los colores del truck y la tipografía, llevados al menú. Además, una propuesta de aplicación de marca con 15 mockups de empaque y señalización.', shots: ['s91-intro'] },
      { t: 'Menú digital', d: '14 categorías y más de 40 platos con fotos, descripciones, precios y etiquetas como “Favorito”.', shots: ['s91-platos', 's91-menu'] },
      { t: 'Experiencia QR', d: 'Un código en la ventanilla del truck abre el menú al instante. El QR nunca cambia, aunque cambien los precios.', shots: [] },
      { t: 'Pedidos por WhatsApp', d: 'El cliente elige y manda su pedido por WhatsApp con un mensaje ya escrito.', shots: ['s91-bebidas'] },
      { t: 'Panel de administración', d: 'La dueña edita platos, cambia precios, sube fotos y marca lo agotado desde su celular.', shots: ['s91-panel', 's91-panel-edit'] },
    ],
    tint: '#6a1d0e',
    phones: [{ src: 's91-bebidas', alt: 'Bebidas con fotos reales en el menú de S91 House Grill' }, { src: 's91-menu', alt: 'Inicio del menú de S91 House Grill con los favoritos de la casa' }, { src: 's91-platos', alt: 'Sección de hamburguesas del menú de S91 con precios' }],
    name: 'S91 House Grill',
    sector: 'Food truck',
    location: 'Orlando, FL',
    year: 2026,
    type: 'Menú digital, panel de administración y marca aplicada',
    categories: ['menus', 'websites', 'branding', 'systems'],
    url: 'https://s91housegrill.com',
    urlLabel: 's91housegrill.com',
    summary: 'Un menú con QR, fotos y pedidos por WhatsApp, más un panel para que la dueña cambie precios y platos desde el celular.',
    og: 'og-s91.jpg',
    problem: [
      'Un food truck nuevo, a días de su gran apertura, con un menú largo: 14 secciones y más de 40 platos entre perros calientes, hamburguesas, cachapas, parrilla, empanadas y bebidas.',
      'Los precios iban a cambiar en las primeras semanas, así que imprimir menús no tenía sentido. Y los clientes ya estaban preguntando por Instagram y WhatsApp qué vendían y cuánto costaba.',
    ],
    solution: [
      'Un menú digital con dominio propio, pensado para abrirse desde un código QR en la ventanilla del truck: categorías con navegación rápida, fotos, descripciones, precios, etiquetas como “Favorito” y un botón para pedir por WhatsApp.',
      'Detrás, un panel de administración donde la dueña edita platos, cambia precios, sube fotos y marca lo que se acabó. Y una propuesta de marca fuera de la pantalla: mockups de empaques, papel de envolver, vasos, uniformes y señalización del truck.',
    ],
    result: [
      'El menú completo vive en un link, s91housegrill.com, y en un QR que no cambia nunca.',
      'Cuando algo se agota, se marca desde el celular y desaparece del menú al instante. Cuando sube un precio, se cambia en segundos, sin reimprimir nada.',
    ],
    features: [
      '14 categorías con navegación fija',
      'Fotos y descripciones de cada plato',
      'Etiquetas: Favorito, Para compartir',
      'Pedido por WhatsApp con mensaje listo',
      'Ubicación con “Cómo llegar”',
      'Botón para compartir el menú',
      'Intro animada con el logo',
      'Panel: editar, reordenar, agotar y subir fotos',
      'Dominio propio y código QR',
      'Propuesta de marca: 15 mockups de empaque y señalización',
    ],
    stack: ['HTML, CSS y JavaScript', 'Supabase (datos, acceso y fotos)', 'GitHub Pages', 'Dominio .com'],
    gallery: [
      { src: 's91-intro', alt: 'Pantalla de entrada del menú de S91 House Grill con el logo en crema sobre fondo oscuro', caption: 'Entrada con el logo animado' },
      { src: 's91-menu', alt: 'Parte superior del menú de S91 con botones de pedido por WhatsApp y cómo llegar, y los favoritos de la casa', caption: 'Inicio del menú: pedido y ubicación a un toque' },
      { src: 's91-platos', alt: 'Sección de hamburguesas del menú de S91 con nombres, descripciones y precios', caption: 'Platos con descripción y precio' },
      { src: 's91-bebidas', alt: 'Sección de bebidas del menú de S91 con fotos de jugos naturales y refrescos', caption: 'Bebidas con fotos reales' },
      { src: 's91-panel', alt: 'Panel de administración de S91 con la lista de categorías y platos', caption: 'Panel de la dueña' },
      { src: 's91-panel-edit', alt: 'Formulario de edición de un plato en el panel de S91, con precio, descripción y disponibilidad', caption: 'Editar un plato desde el celular' },
    ],
  },
  {
    slug: 'zerufy',
    kind: 'client',
    meta: 'Catálogo y sistema / Reventa',
    chapters: [
      { t: 'Catálogo digital', d: 'Categorías, marcas y variantes por talla y color, en español e inglés.', shots: ['zerufy-home'] },
      { t: 'Carrito', d: 'El cliente junta varias piezas y cada pedido lleva su propio número.', shots: [] },
      { t: 'Checkout por WhatsApp', d: 'El pedido llega por WhatsApp con los productos y las tallas ya elegidos.', shots: [] },
      { t: 'Inventario', d: 'Cada modelo con sus colores, tallas y unidades. Avisa lo que queda y lo que se agotó.', shots: ['zerufy-inventario'], note: 'Datos de ejemplo' },
      { t: 'Panel y caja', d: 'Subir y ordenar productos, y un control de caja con ventas, compras y retiros.', shots: ['zerufy-caja'], note: 'Datos de ejemplo' },
    ],
    tint: '#4a0d09',
    phones: [{ src: 'zerufy-caja', alt: 'Control de caja de Zerufy con datos de ejemplo' }, { src: 'zerufy-home', alt: 'Entrada del catálogo de Zerufy' }, { src: 'zerufy-inventario', alt: 'Inventario por modelo de Zerufy con datos de ejemplo' }],
    name: 'Zerufy',
    sector: 'Reventa de lujo y streetwear',
    location: 'Orlando, FL',
    year: null,
    type: 'Catálogo con carrito, panel, caja e inventario',
    categories: ['catalogs', 'ecommerce', 'systems'],
    url: 'https://zerufy.store',
    urlLabel: 'zerufy.store',
    summary: 'Catálogo con carrito y checkout por WhatsApp, panel de productos y control de caja e inventario para una tienda de reventa.',
    og: 'og-zerufy.jpg',
    problem: [
      'Una tienda de reventa de marcas como Louis Vuitton, Chrome Hearts y Cartier que vendía por WhatsApp, Instagram, TikTok y Marketplace.',
      'Cada venta empezaba mandando fotos y precios uno por uno, y no había un solo lugar para ver el catálogo, el dinero que entraba y salía, y lo que quedaba en inventario.',
    ],
    solution: [
      'Un catálogo propio con categorías, variantes por talla y color, carrito y checkout por WhatsApp con número de pedido. Disponible en español e inglés.',
      'Un panel para subir y ordenar productos, y dos herramientas internas: un control de caja (ventas, compras y retiros) y un inventario por modelo que avisa lo que queda y lo que se agotó.',
    ],
    result: [
      'Zerufy fue el primer negocio donde probamos el sistema. Todo el catálogo se comparte con un link, zerufy.store, y los pedidos llegan por WhatsApp con los productos y tallas ya elegidos.',
      'De este proyecto salió la base que hoy usan los demás catálogos que construimos.',
    ],
    features: [
      'Catálogo por categorías y marcas',
      'Variantes por talla y color',
      'Carrito con número de pedido',
      'Checkout por WhatsApp',
      'Español e inglés',
      'Panel de productos',
      'Control de caja',
      'Inventario por modelo',
      'Dominio propio',
    ],
    stack: ['HTML, CSS y JavaScript', 'Supabase', 'GitHub Pages', 'Dominio .store'],
    gallery: [
      { src: 'zerufy-home', alt: 'Pantalla de entrada del catálogo de Zerufy con el nombre en rojo sobre fondo negro', caption: 'Entrada del catálogo' },
      { src: 'zerufy-caja', alt: 'Herramienta de caja de Zerufy con caja actual, ventas, compras y formulario de nuevo movimiento', caption: 'Control de caja (datos de ejemplo)' },
      { src: 'zerufy-inventario', alt: 'Herramienta de inventario de Zerufy con modelos, colores, tallas y unidades', caption: 'Inventario por modelo (datos de ejemplo)' },
    ],
  },
  {
    slug: 'amh-store',
    kind: 'client',
    meta: 'Catálogo con marca / Joyería',
    chapters: [
      { t: 'Catálogo con marca propia', d: 'Violeta, tipografía condensada y un fondo animado: una identidad hecha para relojes y joyería.', web: 'amh-desktop' },
      { t: 'Páginas de producto', d: 'Cada pieza tiene su propio link para compartirla directo en historias o chats.', shots: [] },
      { t: 'Carrito', d: 'El cliente arma su pedido con varias piezas antes de escribir.', shots: [] },
      { t: 'Pedidos por WhatsApp', d: 'El pedido llega armado por WhatsApp, también en inglés.', shots: [] },
      { t: 'Sistema de administración', d: 'Su propio panel y sus propios datos, sobre la misma plataforma que Zerufy.', shots: ['amh-home'] },
    ],
    tint: '#2c1766',
    web: { src: 'amh-desktop', alt: 'Portada del catálogo de AMH Store en computadora', h: 540 },
    phones: [{ src: 'amh-home', alt: 'Entrada del catálogo de AMH Store en el celular' }],
    name: 'AMH Store',
    sector: 'Relojes, joyería y accesorios',
    location: null,
    year: null,
    type: 'Catálogo con carrito y panel',
    categories: ['catalogs', 'ecommerce'],
    url: 'https://amhstore.store',
    urlLabel: 'amhstore.store',
    summary: 'Catálogo con identidad propia para una tienda de relojes y joyería, con carrito, pedidos por WhatsApp y links directos a cada pieza.',
    og: 'og-amh.jpg',
    problem: [
      'Una tienda de relojes, joyería y accesorios que vendía por redes y necesitaba un catálogo propio, con una imagen a la altura de las piezas.',
    ],
    solution: [
      'Un catálogo con su propia identidad visual (violeta, tipografía condensada y un fondo animado), carrito, pedido por WhatsApp, versión en inglés y links que abren directamente una pieza para compartirla en historias o chats.',
      'Funciona sobre la misma plataforma que Zerufy, con su propio panel y sus propios datos.',
    ],
    result: [
      'La tienda tiene su dominio, amhstore.store, y su propio panel para manejar productos y precios.',
      'Como comparte la base del sistema con otros negocios, cada mejora que hacemos a la plataforma también le llega a ella.',
    ],
    features: [
      'Identidad visual propia',
      'Fondo animado',
      'Catálogo por categorías',
      'Carrito y pedido por WhatsApp',
      'Link directo a cada producto',
      'Español e inglés',
      'Panel de administración',
      'Dominio propio',
    ],
    stack: ['HTML, CSS y JavaScript', 'Canvas', 'Supabase', 'GitHub Pages'],
    gallery: [
      { src: 'amh-desktop', wide: true, alt: 'Portada del catálogo de AMH Store en computadora, con el nombre en blanco y violeta sobre fondo estrellado', caption: 'Portada en computadora' },
    ],
  },
  {
    slug: 'panel-district',
    kind: 'system',
    meta: 'Plataforma propia / Sistemas',
    tint: '#2a2a2a',
    phones: [{ src: 's91-panel', alt: 'Panel de administración con categorías y platos' }, { src: 's91-panel-edit', alt: 'Edición de un plato desde el celular' }, { src: 'zerufy-inventario', alt: 'Módulo de inventario con datos de ejemplo' }],
    name: 'Panel District',
    sector: 'Plataforma propia',
    location: 'Orlando, FL',
    year: 2026,
    type: 'Plataforma de administración para varios negocios',
    categories: ['systems'],
    url: null,
    summary: 'El sistema detrás de cada catálogo y menú: un panel por negocio, datos separados y módulos de caja e inventario.',
    og: 'og-panel.jpg',
    problem: [
      'Cada negocio necesitaba cambiar precios, fotos y productos sin tener que escribirnos, y cada uno tiene datos que nadie más debe ver: costos, ganancias, clientes.',
      'Construir un sistema desde cero para cada cliente hubiera sido lento y caro para ellos.',
    ],
    solution: [
      'Una sola plataforma que atiende a varios negocios. Cada uno tiene su tienda, su panel y su acceso con correo y contraseña. Las reglas de seguridad de la base de datos hacen que cada dueño solo vea lo suyo, y que el público solo vea lo que está publicado.',
      'Encima de la base van módulos opcionales: control de caja, inventario y ajustes de marca como colores, textos y horario.',
    ],
    result: [
      'Un negocio nuevo arranca sobre una base ya probada en vez de empezar de cero. Hoy la plataforma atiende a Zerufy, AMH Store y S91 House Grill.',
      'Cada mejora que hacemos a la plataforma les llega a todos los negocios a la vez.',
    ],
    features: [
      'Un panel por negocio',
      'Acceso con correo y contraseña',
      'Datos separados por negocio',
      'Reglas de seguridad en la base de datos',
      'Productos, categorías y orden',
      'Agotado y disponible con un toque',
      'Fotos optimizadas al subirlas',
      'Ajustes de marca',
      'Módulos de caja e inventario',
    ],
    stack: ['Supabase (Postgres, Auth, Storage)', 'Row Level Security', 'JavaScript', 'GitHub Pages'],
    gallery: [
      { src: 's91-panel', alt: 'Panel de administración con categorías y platos de S91 House Grill', caption: 'Panel de un restaurante' },
      { src: 's91-panel-edit', alt: 'Edición de un plato con nombre, precio, descripción, categoría y disponibilidad', caption: 'Edición de un producto' },
      { src: 'zerufy-inventario', alt: 'Módulo de inventario con variantes por color y talla', caption: 'Módulo de inventario (datos de ejemplo)' },
    ],
  },
];

// Conceptos: prototipos funcionales que diseñamos para presentar a negocios.
// No son clientes: en el sitio siempre dicen "Concepto".
const concepts = [
  {
    slug: 'jircars',
    kind: 'concept',
    name: 'Jircars',
    meta: 'Concepto / Concesionario',
    sector: 'Venta de autos',
    location: 'Valencia, Carabobo',
    type: 'Inventario de vehículos con contacto por WhatsApp',
    categories: ['catalogs', 'websites'],
    summary: 'Inventario de vehículos con filtros por tipo, búsqueda, ficha de cada auto con año, millaje y caja, y contacto por WhatsApp.',
    tint: '#3a2c0c',
    web: { src: 'jircars-desktop', alt: 'Portada de Jircars en computadora: “Encuentra tu próximo auto”' },
    phones: [{ src: 'jircars-intro', alt: 'Portada del inventario de Jircars en el celular' }, { src: 'jircars-catalogo', alt: 'Lista de vehículos de Jircars con año, millaje y caja' }],
    features: ['Inventario por tipo: SUV, pickup, sedán', 'Búsqueda por marca o modelo', 'Ficha con año, millaje y caja', 'Estado: disponible o reservado', 'Contacto por WhatsApp en cada auto', 'Versión para computadora y celular'],
  },
  {
    slug: 'aureon',
    kind: 'concept',
    name: 'Aureon',
    meta: 'Concepto / Fragancias',
    sector: 'Fragancias de lujo',
    type: 'Catálogo con carrito y pedido por WhatsApp',
    categories: ['catalogs', 'ecommerce'],
    summary: 'Catálogo de perfumes por familia olfativa, con etiquetas de oferta y agotado, carrito y pedido confirmado por WhatsApp.',
    tint: '#33260a',
    web: { src: 'aureon-desktop', alt: 'Portada de Aureon en computadora: “Fragancias que se recuerdan”' },
    phones: [{ src: 'aureon-intro', alt: 'Entrada del catálogo de Aureon con el logo dorado' }, { src: 'aureon-catalogo', alt: 'Catálogo de fragancias de Aureon' }],
    features: ['Colección por familia olfativa', 'Etiquetas de oferta y agotado', 'Carrito', 'Pedido confirmado por WhatsApp', 'Intro con la marca'],
  },
  {
    slug: 'alta-pinta',
    kind: 'concept',
    name: 'Alta Pinta',
    meta: 'Concepto / Ropa urbana',
    sector: 'Ropa urbana',
    type: 'Tienda con identidad de marca y pedido por WhatsApp',
    categories: ['ecommerce', 'catalogs', 'branding'],
    summary: 'Catálogo con identidad de marca propia: intro animada, categorías, favoritos y pedido armado que se envía por WhatsApp.',
    tint: '#262626',
    web: { src: 'altapinta-desktop', alt: 'Portada de Alta Pinta en computadora: “Viste con pinta”' },
    phones: [{ src: 'altapinta-intro', alt: 'Entrada del catálogo de Alta Pinta con el logo a pincel' }, { src: 'altapinta-catalogo', alt: 'Productos del catálogo de Alta Pinta' }],
    features: ['Intro animada con el logo', 'Categorías: camisetas, hoodies, gorras, tenis', 'Favoritos', 'Carrito', 'Pedido armado por WhatsApp'],
  },
  {
    slug: 'liz-boutique',
    kind: 'concept',
    name: 'Liz Boutique',
    meta: 'Concepto / Moda',
    sector: 'Moda y accesorios',
    type: 'Catálogo con ofertas y pedido por WhatsApp',
    categories: ['catalogs', 'ecommerce'],
    summary: 'Vestidos, zapatos, bolsos y accesorios en un catálogo con ofertas, novedades y pedido por WhatsApp.',
    tint: '#4a2630',
    web: { src: 'liz-desktop', alt: 'Portada de Liz Boutique en computadora con novedades' },
    phones: [{ src: 'liz-intro', alt: 'Entrada del catálogo de Liz Boutique' }, { src: 'liz-catalogo', alt: 'Catálogo de Liz Boutique con ofertas y novedades' }],
    features: ['Categorías con íconos', 'Ofertas y novedades', 'Favoritos', 'Carrito', 'Pedido por WhatsApp'],
  },
  {
    slug: 'carpashop',
    kind: 'concept',
    name: 'CarpaShop',
    meta: 'Concepto / Accesorios',
    sector: 'Accesorios para celular',
    type: 'Tienda con búsqueda y pedido por WhatsApp',
    categories: ['ecommerce', 'catalogs'],
    summary: 'Cargadores, cables, audífonos y fundas con búsqueda, categorías, agotados y pedido por WhatsApp.',
    tint: '#0d2448',
    web: { src: 'carpashop-desktop', alt: 'Portada de CarpaShop en computadora: “Accesorios para tu teléfono, con actitud”' },
    phones: [{ src: 'carpashop-intro', alt: 'Entrada del catálogo de CarpaShop' }, { src: 'carpashop-catalogo', alt: 'Inicio de CarpaShop con botones de catálogo y WhatsApp' }],
    features: ['Búsqueda de productos', 'Categorías con contador', 'Etiquetas: más vendido, oferta, nuevo', 'Carrito', 'Pago al recibir, pedido por WhatsApp'],
  },
];

// Orden del portafolio: lo más fuerte primero.
const ORDER = ['s91-house-grill', 'jircars', 'zerufy', 'aureon', 'amh-store', 'alta-pinta', 'liz-boutique', 'carpashop', 'panel-district'];
projects.push(...concepts);
projects.sort((a, b) => ORDER.indexOf(a.slug) - ORDER.indexOf(b.slug));
