// Servicios. Cada uno genera su propia página (path) y aparece en /services/.
// status: 'available' | 'soon'

export const services = [
  {
    key: 'websites',
    path: '/websites/',
    name: 'Páginas web',
    icon: 'web',
    status: 'available',
    outcome: 'Una presencia en internet a la altura de tu marca.',
    lead: 'Tu sitio con lo que un cliente busca antes de visitarte o comprarte: qué haces, precios, horarios, ubicación y cómo escribirte. Diseñado para el celular y listo para aparecer en Google.',
    forWho: ['Restaurantes', 'Barberías', 'Salones de belleza', 'Tiendas', 'Profesionales', 'Marcas personales', 'Negocios locales'],
    benefits: [
      { t: 'Te toman en serio', d: 'Un sitio propio con tu dominio da más confianza que un perfil de redes o un link genérico.' },
      { t: 'Te encuentran en Google', d: 'Textos, estructura y datos preparados para búsquedas como “barbería en Orlando” o “restaurante cerca de mí”.' },
      { t: 'Te escriben listos', d: 'Botones directos a WhatsApp, llamada, mapa e Instagram. Menos preguntas repetidas, más citas y ventas.' },
    ],
    features: [
      { t: 'Diseño a medida', d: 'Tus colores, tu logo y tu forma de hablar. Sin plantillas.' },
      { t: 'Pensado para celular', d: 'Se ve y se usa bien en teléfono, tablet y computadora.' },
      { t: 'Dominio propio', d: 'tunegocio.com, conectado y con conexión segura.' },
      { t: 'SEO local', d: 'Títulos, descripciones y datos estructurados para Google.' },
      { t: 'WhatsApp, Instagram y mapa', d: 'Todo a un toque de distancia.' },
      { t: 'Formularios', d: 'Citas, cotizaciones o contacto, directo a tu WhatsApp o correo.' },
      { t: 'Carga rápida', d: 'Funciona bien aunque el cliente tenga mala señal.' },
      { t: 'Analítica', d: 'Sabes cuánta gente entra y de dónde viene.' },
    ],
    examples: ['s91-house-grill'],
    price: { label: 'Cotización según el proyecto' },
    seo: {
      title: 'Diseño de páginas web para negocios en Orlando | District Studio',
      description: 'Páginas web a medida para restaurantes, barberías, salones, tiendas y negocios locales. Rápidas en el celular, con dominio propio y listas para Google.',
    },
  },
  {
    key: 'menus',
    path: '/menus/',
    name: 'Menús digitales',
    icon: 'menu',
    status: 'available',
    outcome: 'Tu menú en un QR, siempre con el precio correcto.',
    lead: 'Un menú con fotos, precios y categorías que tus clientes abren desde un código QR o un link. Cuando cambia un precio o se acaba un plato, lo cambias tú desde el celular y listo.',
    forWho: ['Restaurantes', 'Food trucks', 'Cafeterías', 'Panaderías', 'Heladerías', 'Bares'],
    benefits: [
      { t: 'Nunca más reimprimir', d: 'Cambias precios, platos y fotos desde tu panel. El QR sigue siendo el mismo.' },
      { t: 'Pedidos más rápidos', d: 'El cliente ve el menú con fotos y te escribe por WhatsApp sabiendo lo que quiere.' },
      { t: 'Se ve como tu marca', d: 'Tus colores, tu logo y tu estilo, no un menú genérico de plataforma.' },
    ],
    features: [
      { t: 'Categorías', d: 'Hamburguesas, bebidas, postres… con navegación rápida entre secciones.' },
      { t: 'Fotos de los platos', d: 'Optimizadas para que carguen rápido.' },
      { t: 'Descripciones y precios', d: 'Ingredientes, qué incluye cada plato y etiquetas como “Favorito”.' },
      { t: 'Botón de pedido', d: 'Abre WhatsApp con el mensaje listo para enviar.' },
      { t: 'Código QR', d: 'Para la mesa, la ventanilla del truck, volantes y empaques.' },
      { t: 'Ubicación y horarios', d: 'Con botón “Cómo llegar” a Google Maps.' },
      { t: 'Redes sociales', d: 'Instagram, TikTok y un botón para compartir el menú.' },
      { t: 'Panel de administración', d: 'Editas platos, marcas agotados y reordenas el menú sin llamarnos.' },
    ],
    examples: ['s91-house-grill'],
    price: { from: 250, monthly: 30 },
    seo: {
      title: 'Menú digital con QR para restaurantes y food trucks | District Studio',
      description: 'Menú digital con fotos, precios, código QR y pedidos por WhatsApp. Cambias precios y platos agotados desde tu celular. Para restaurantes y food trucks.',
    },
  },
  {
    key: 'catalogs',
    path: '/catalogs/',
    name: 'Catálogos digitales',
    icon: 'catalog',
    status: 'available',
    outcome: 'Un solo link con todo lo que vendes.',
    lead: 'Mucho más que un PDF: un catálogo con fotos, categorías, variantes y precios, donde el cliente busca, filtra y te hace el pedido. Lo compartes en tu bio, en WhatsApp o en un QR.',
    forWho: ['Tiendas de ropa', 'Reventa y streetwear', 'Joyería y relojes', 'Accesorios', 'Concesionarios', 'Distribuidores'],
    benefits: [
      { t: 'Dejas de mandar fotos una por una', d: 'El cliente ve todo el catálogo por su cuenta, a la hora que quiera.' },
      { t: 'Pedidos claros', d: 'Llegan a tu WhatsApp con producto, talla, color y cantidad.' },
      { t: 'Siempre al día', d: 'Subes productos y cambias precios desde tu panel en segundos.' },
    ],
    features: [
      { t: 'Fotos y categorías', d: 'Tu inventario ordenado como lo buscaría un cliente.' },
      { t: 'Variantes', d: 'Tallas, colores o modelos, cada uno con su precio y disponibilidad.' },
      { t: 'Búsqueda y filtros', d: 'Por categoría, marca o precio.' },
      { t: 'Favoritos', d: 'El cliente guarda lo que le gusta para decidir después.' },
      { t: 'WhatsApp e Instagram', d: 'Un botón en cada producto.' },
      { t: 'Carrito o cotización', d: 'Pedido completo o solicitud de precio, según cómo vendas.' },
      { t: 'Link por producto', d: 'Comparte un producto exacto en historias o chats.' },
      { t: 'Panel de administración', d: 'Productos, precios, fotos y categorías en tus manos.' },
    ],
    examples: ['zerufy', 'amh-store'],
    price: { from: 250, monthly: 30 },
    seo: {
      title: 'Catálogo digital para tiendas: un link con todos tus productos | District Studio',
      description: 'Catálogo online con fotos, variantes, precios, búsqueda y pedidos por WhatsApp. Un solo link para tu bio, tus chats y tus clientes.',
    },
  },
  {
    key: 'ecommerce',
    path: '/ecommerce/',
    name: 'Tiendas online',
    icon: 'bag',
    status: 'available',
    outcome: 'Vende a cualquier hora sin contestar cada mensaje.',
    lead: 'Una tienda completa: carrito, checkout, pagos con tarjeta, inventario y pedidos organizados. Para cuando tu negocio ya no cabe en el chat.',
    forWho: ['Tiendas de ropa', 'Marcas propias', 'Joyería y accesorios', 'Productos de belleza', 'Negocios con envíos'],
    benefits: [
      { t: 'Cobras sin estar pendiente', d: 'El cliente paga en línea y a ti te llega el pedido listo para preparar.' },
      { t: 'Inventario que no falla', d: 'El stock baja con cada venta, así no vendes lo que ya no tienes.' },
      { t: 'Todo en un solo lugar', d: 'Pedidos, clientes, envíos y cupones en tu panel.' },
    ],
    features: [
      { t: 'Carrito y checkout', d: 'Un proceso de compra corto, pensado para el celular.' },
      { t: 'Pagos en línea', d: 'Tarjetas con Stripe o PayPal. También pedido por WhatsApp.' },
      { t: 'Inventario', d: 'Existencias por producto y variante, en tiempo real.' },
      { t: 'Variantes', d: 'Tallas, colores y modelos con su propio stock.' },
      { t: 'Cupones', d: 'Descuentos por código, por fecha o por cliente.' },
      { t: 'Pedidos', d: 'Nuevo, pagado, enviado: sabes en qué va cada uno.' },
      { t: 'Envíos', d: 'Costo por zona, envío nacional o retiro en persona.' },
      { t: 'Redes sociales', d: 'Integración con Instagram, TikTok y Meta Pixel.' },
    ],
    examples: ['zerufy', 'amh-store'],
    price: { label: 'Cotización según el proyecto' },
    seo: {
      title: 'Tiendas online (e-commerce) para pequeños negocios | District Studio',
      description: 'Tiendas online con carrito, pagos con tarjeta, inventario, cupones y pedidos organizados. E-commerce a medida para negocios que venden por redes.',
    },
  },
  {
    key: 'systems',
    path: '/systems/',
    name: 'Sistemas a medida',
    icon: 'system',
    status: 'available',
    outcome: 'Pedidos, clientes e inventario en un solo lugar.',
    lead: 'Paneles y herramientas hechas para la forma en que trabaja tu negocio: pedidos, reservaciones, inventario, caja y clientes. Menos notas en el teléfono y menos capturas perdidas.',
    forWho: ['Negocios con inventario', 'Restaurantes con pedidos', 'Barberías y salones con citas', 'Equipos de ventas', 'Negocios con varias sucursales'],
    benefits: [
      { t: 'Sabes cómo va tu negocio', d: 'Ventas, gastos y caja al día en un solo tablero.' },
      { t: 'Menos trabajo repetido', d: 'Automatizaciones que avisan, registran y ordenan por ti.' },
      { t: 'Crece contigo', d: 'Empiezas con un módulo y agregas otros cuando los necesites.' },
    ],
    features: [
      { t: 'Panel de administración', d: 'Acceso con usuario y contraseña, desde el celular.' },
      { t: 'Productos', d: 'Altas, precios, fotos, agotados y orden de aparición.' },
      { t: 'Clientes', d: 'Historial de compras y datos de contacto.' },
      { t: 'Pedidos', d: 'Todos los pedidos en una lista, con su estado.' },
      { t: 'Reservaciones', d: 'Citas y reservas con horarios disponibles.' },
      { t: 'Caja e inventario', d: 'Ventas, compras, retiros y existencias por modelo.' },
      { t: 'Dashboard', d: 'Los números importantes a primera vista.' },
      { t: 'Integraciones', d: 'WhatsApp, Google Calendar, Notion, Airtable y correo.' },
    ],
    examples: ['panel-district', 'zerufy'],
    price: { label: 'Cotización según el proyecto' },
    seo: {
      title: 'Sistemas a medida y paneles de administración para negocios | District Studio',
      description: 'Paneles de administración, control de inventario y caja, pedidos, reservaciones y automatizaciones hechos a la medida de tu negocio.',
    },
  },
  {
    key: 'apps',
    path: '/apps/',
    name: 'Apps móviles',
    icon: 'phone',
    status: 'soon',
    outcome: 'Tu negocio en la pantalla de inicio de tus clientes.',
    lead: 'Apps para iPhone y Android para pedir, reservar, acumular puntos o recibir avisos. Es el siguiente paso para los negocios que ya tienen su plataforma con nosotros.',
    statusNote: 'Estamos preparando esta línea. Si ya tienes la idea, cuéntanosla y la planificamos contigo.',
    forWho: ['Restaurantes', 'Tiendas', 'Gimnasios y membresías', 'Barberías y salones', 'Negocios con clientes frecuentes'],
    benefits: [
      { t: 'Clientes que vuelven', d: 'Puntos, membresías y promociones que llegan directo al teléfono.' },
      { t: 'Pedidos en dos toques', d: 'El cliente guarda su pedido favorito y lo repite cuando quiera.' },
      { t: 'Usa lo que ya tienes', d: 'La app se conecta al mismo panel y productos de tu web o catálogo.' },
    ],
    features: [
      { t: 'iPhone y Android', d: 'Publicada en App Store y Google Play.' },
      { t: 'Pedidos', d: 'Menú o catálogo con carrito dentro de la app.' },
      { t: 'Membresías y puntos', d: 'Programas de lealtad y beneficios para clientes frecuentes.' },
      { t: 'Notificaciones', d: 'Avisos de promociones, pedidos listos o citas.' },
      { t: 'Reservaciones', d: 'Citas y reservas desde el teléfono.' },
      { t: 'Conectada a tu panel', d: 'Los mismos productos y precios que ya manejas.' },
    ],
    examples: [],
    price: { label: 'Próximamente' },
    seo: {
      title: 'Apps móviles para restaurantes y tiendas (iPhone y Android) | District Studio',
      description: 'Apps para iPhone y Android con pedidos, membresías, puntos y notificaciones, conectadas al mismo panel de tu negocio.',
    },
  },
];

// Planes con precio fijo (catálogos y menús). Lo demás se cotiza.
export const plans = [
  {
    key: 'base',
    name: 'Plan Base',
    setup: 250,
    monthly: 30,
    for: 'Para empezar a vender con tu propio link.',
    includes: [
      'Catálogo o menú digital con tu marca',
      'Carrito o pedido directo por WhatsApp',
      'Panel para cambiar productos, precios y fotos',
      'Versión para celular, tablet y computadora',
      'Hosting y soporte incluidos en la mensualidad',
    ],
  },
  {
    key: 'completo',
    name: 'Plan Completo',
    setup: 400,
    monthly: 50,
    featured: true,
    for: 'Para llevar el control del negocio, no solo de la vitrina.',
    includes: [
      'Todo lo del Plan Base',
      'Control de caja: ventas, compras y retiros',
      'Inventario en tiempo real por producto y variante',
      'Hosting y soporte incluidos en la mensualidad',
    ],
  },
  {
    key: 'medida',
    name: 'A medida',
    setup: null,
    monthly: null,
    for: 'Páginas web completas, tiendas con pagos en línea, sistemas y automatizaciones.',
    includes: [
      'Propuesta con alcance, precio y fecha de entrega',
      'Diseño y desarrollo según tu operación',
      'Integraciones con tus herramientas',
      'Mantenimiento mensual opcional',
    ],
  },
];
