// Páginas por tipo de negocio: /negocios/<slug>/
// Formato del pitch de Zerufy Studio: el problema de hoy, lo que te damos,
// tu panel (demostración animada), cómo se vende, tú vs nosotros. Sin precios.
// Regla: todos los proyectos se entregan con panel de administración.

export const verticals = [
  {
    slug: 'restaurantes',
    preview: 's91-menu',
    need: 'menus',
    name: 'Restaurantes y food trucks',
    short: 'Restaurantes',
    for: 'Para restaurantes, food trucks y cafeterías',
    title: ['Tu menú,', 'siempre con el <em>precio correcto.</em>'],
    lead: 'Un menú con fotos y precios que tu cliente abre con un QR o un link. Se acabó un plato o subió un precio: lo cambias tú desde el celular y listo.',
    wa: 'Hola Zerufy Studio, tengo un restaurante y quiero mi menú digital.',
    hero: { phone: 's91-menu-scroll', tall: 3600, scroll: true, label: 'S91 House Grill · En línea' },
    pains: [
      ['Reimprimir el menú cada vez que sube un precio', 'Cambias el precio en tu panel y el QR sigue siendo el mismo.'],
      ['Mandar fotos del menú por WhatsApp a cada cliente', 'Un link con todo el menú, con fotos, para tu bio y tus chats.'],
      ['“¿Todavía tienen el especial?” todo el día', 'Marcas agotado y el plato deja de salir al instante.'],
      ['Pedidos que llegan incompletos o confusos', 'El pedido te llega por WhatsApp ya escrito, plato por plato.'],
    ],
    gives: [
      'Tu menú con tu logo, tus colores, fotos y precios',
      'Código QR para la mesa, la ventanilla o los volantes',
      'Botón para pedir por WhatsApp con el pedido ya escrito',
      'Ubicación, horarios y redes en el mismo lugar',
      'Tu panel de administración para cambiarlo todo tú mismo',
    ],
    demo: {
      brand: 'Tu restaurante',
      icon: 'menu',
      off: 'Agotado',
      items: [
        { n: 'Hamburguesa clásica', m: 'Hamburguesas', p: '$12.99' },
        { n: 'Papas con queso', m: 'Acompañantes', p: '$5.50' },
        { n: 'Batido de fresa', m: 'Bebidas', p: '$6.00' },
      ],
      add: { n: 'Especial del día', m: 'Solo hoy', p: '$14.99' },
      steps: [
        { a: 'price', i: 0, to: '$13.49', cap: 'Cambias un precio' },
        { a: 'off', i: 1, cap: 'Marcas un plato agotado' },
        { a: 'add', cap: 'Subes el especial del día' },
      ],
    },
    how: [
      { t: 'Tu cliente escanea el QR', d: 'O abre tu link. No descarga ninguna app.' },
      { t: 'Ve el menú completo', d: 'Con fotos, precios correctos y lo que está disponible hoy.' },
      { t: 'Te escribe su pedido', d: 'Por WhatsApp, ya armado y sin confusiones.' },
      { t: 'Tú lo preparas y cobras', d: 'Como siempre: efectivo, Zelle o como trabajes.' },
    ],
    control: ['Platos, fotos y descripciones', 'Precios', 'Agotados', 'Secciones y orden del menú'],
    examples: ['s91-house-grill'],
    faq: [
      { q: '¿Mis clientes tienen que descargar algo?', a: 'No. Escanean el QR o tocan tu link y el menú abre en el navegador del celular.' },
      { q: '¿Si cambio un precio tengo que imprimir otro QR?', a: 'No. El QR es siempre el mismo. Cambias el precio en tu panel y se actualiza al instante.' },
      { q: '¿El menú cobra por mí?', a: 'No. El pedido te llega por WhatsApp y el pago lo manejas tú, como hoy.' },
      { q: '¿Y si algo deja de funcionar?', a: 'Nos escribes y lo arreglamos. El soporte y el mantenimiento van incluidos en la mensualidad.' },
    ],
    close: { q: '¿Tienes un restaurante?', t: 'Pongamos tu menú en <em>línea.</em>' },
  },
  {
    slug: 'tiendas',
    preview: 'offsuite-catalogo',
    need: 'catalogs',
    name: 'Tiendas de ropa y reventa',
    short: 'Tiendas',
    for: 'Para tiendas de ropa, reventa, perfumes y accesorios',
    title: ['Tu tienda', 'en un solo <em>link.</em>'],
    lead: 'Un catálogo tipo app con todos tus productos, tallas y precios. Tu cliente arma su pedido y te llega por WhatsApp. Tú subes y cambias todo desde tu panel.',
    wa: 'Hola Zerufy Studio, tengo una tienda y quiero mi catálogo.',
    hero: { phone: 'offsuite-scroll', tall: 3600, scroll: true, label: 'Offsuite · Concepto' },
    pains: [
      ['Mandar fotos una por una cada vez que preguntan', 'Un link con todo tu catálogo para tu bio y tus historias.'],
      ['“¿Precio?” “¿Qué tallas tienes?” cien veces al día', 'Cada producto dice su precio y sus tallas.'],
      ['Vender algo que ya no tienes', 'Lo marcas agotado y deja de salir.'],
      ['Pedidos regados entre DMs y chats', 'El pedido llega por WhatsApp con producto, talla, cantidad y total.'],
    ],
    gives: [
      'Un catálogo tipo app con tu logo y tus colores',
      'Fotos, precios, categorías y tallas o variantes',
      'Carrito: el pedido te llega por WhatsApp con todo escrito',
      'Un solo link para tu bio, tus historias y tus chats',
      'Tu panel de administración para manejarlo tú mismo',
    ],
    demo: {
      brand: 'Tu tienda',
      icon: 'bag',
      off: 'Agotado',
      items: [
        { n: 'Hoodie negro', m: 'S · M · L · XL', p: '$75' },
        { n: 'Tee oversize', m: 'M · L', p: '$35' },
        { n: 'Gorra bordada', m: 'Talla única', p: '$30' },
      ],
      add: { n: 'Cargo pants', m: 'Nuevo drop', p: '$65' },
      steps: [
        { a: 'price', i: 1, to: '$29', cap: 'Pones un precio de oferta' },
        { a: 'off', i: 2, cap: 'Marcas un producto agotado' },
        { a: 'add', cap: 'Subes el nuevo drop' },
      ],
    },
    how: [
      { t: 'Tu cliente ve todo el catálogo', d: 'Desde su celular, sin que le mandes fotos.' },
      { t: 'Arma su pedido', d: 'Productos, tallas y cantidades en el carrito.' },
      { t: 'Te llega por WhatsApp', d: 'Con todo escrito y el total.' },
      { t: 'Tú cierras la venta', d: 'Confirmas, cobras y entregas como trabajes.' },
    ],
    control: ['Productos y fotos', 'Precios y ofertas', 'Tallas y agotados', 'Categorías'],
    examples: ['offsuite', 'zerufy', 'amh-store', 'aureon', 'alta-pinta'],
    faq: [
      { q: '¿Puedo subir productos yo mismo?', a: 'Sí. Desde tu panel subes fotos, precios y tallas en segundos, desde el celular.' },
      { q: '¿El catálogo cobra por mí?', a: 'No. El pedido te llega por WhatsApp y el pago lo acuerdas tú con tu cliente.' },
      { q: '¿Puedo llevar caja e inventario?', a: 'Sí, se puede agregar control de caja e inventario por producto y talla.' },
      { q: '¿Y si algo deja de funcionar?', a: 'Nos escribes y lo arreglamos. El soporte y el mantenimiento van incluidos en la mensualidad.' },
    ],
    close: { q: '¿Tienes una tienda?', t: 'Pongamos tu catálogo en <em>línea.</em>' },
  },
  {
    slug: 'concesionarios',
    preview: 'jircars-catalogo',
    need: 'catalogs',
    name: 'Concesionarios',
    short: 'Concesionarios',
    for: 'Para concesionarios y lotes de vehículos',
    title: ['Tu lote,', 'siempre al <em>día.</em>'],
    lead: 'Todos tus vehículos con fotos, precio y ficha en un solo link. Tu cliente los ve desde el celular antes de pisar el lote, y te escribe por el carro que le interesa.',
    wa: 'Hola Zerufy Studio, tengo un concesionario y quiero el catálogo de mi inventario.',
    hero: { web: 'jircars-desktop', phone: 'jircars-catalogo', tall: 1169, label: 'Jircars · Concepto' },
    pains: [
      ['Mandar fotos de carros sueltas por WhatsApp', 'Todo tu inventario en un link, con fotos y ficha.'],
      ['“¿Tienes disponible el Toyota 2019?” y buscarlo en el chat', 'Tu cliente ve qué hay disponible sin preguntarte.'],
      ['Seguir recibiendo mensajes por un carro que ya vendiste', 'Lo marcas vendido y sale del catálogo al instante.'],
      ['Sin un lugar serio donde mandar al cliente', 'Un catálogo con tu marca que da confianza.'],
    ],
    gives: [
      'Catálogo tipo app de todo tu inventario, con tu logo y tus colores',
      'Cada vehículo con fotos, precio, año, millaje y ficha',
      'Botón de WhatsApp en cada vehículo: te escriben por ESE carro',
      'Organizado por tipo: sedán, SUV, pickup',
      'Tu panel de administración para subir, editar y marcar vendidos tú mismo',
    ],
    demo: {
      brand: 'Tu lote',
      icon: 'catalog',
      off: 'Vendido',
      items: [
        { n: 'Toyota Tacoma 2019', m: '62,000 mi · Automática', p: '$24,900' },
        { n: 'Honda Civic 2020', m: '41,000 mi · Automática', p: '$18,500' },
        { n: 'Ford Explorer 2018', m: '77,000 mi · 4x4', p: '$21,000' },
      ],
      add: { n: 'Jeep Wrangler 2021', m: '30,000 mi · 4x4', p: '$29,900' },
      steps: [
        { a: 'price', i: 1, to: '$17,900', cap: 'Bajas un precio' },
        { a: 'off', i: 2, cap: 'Marcas un carro vendido' },
        { a: 'add', cap: 'Subes un carro nuevo' },
      ],
    },
    how: [
      { t: 'Tu cliente ve el lote completo', d: 'Todos los vehículos disponibles, con fotos y precio, desde su celular.' },
      { t: 'Pregunta por el que le interesa', d: 'Un botón de WhatsApp en cada vehículo: te llega sabiendo cuál quiere.' },
      { t: 'Tú cierras la venta', d: 'Por WhatsApp, en el lote, como trabajes tú.' },
      { t: 'Lo marcas vendido', d: 'Sale del catálogo al instante y nadie más pregunta por él.' },
    ],
    control: ['Vehículos y fotos', 'Precios', 'Vendidos', 'Tipos y orden'],
    examples: ['jircars'],
    faq: [
      { q: '¿Necesito saber de tecnología?', a: 'Para nada. Te lo entregamos armado. Subir un carro es tan fácil como subir una foto a Instagram.' },
      { q: '¿Puedo cambiar mi inventario yo mismo?', a: 'Sí, cuando quieras: carros nuevos, precios, fotos y vendidos, desde tu panel.' },
      { q: '¿Cómo cierro la venta?', a: 'Como tú quieras: WhatsApp, llamada o en el lote. El catálogo no cobra por ti: hace que el cliente llegue ya interesado en un vehículo.' },
      { q: '¿Y si algo deja de funcionar?', a: 'Nos escribes y lo arreglamos. El soporte y el mantenimiento van incluidos en la mensualidad.' },
    ],
    close: { q: '¿Tienes un concesionario?', t: 'Pongamos tu lote en <em>línea.</em>' },
  },
  {
    slug: 'citas',
    preview: 'ibrows-hero',
    need: 'booking',
    name: 'Negocios con citas',
    short: 'Citas y servicios',
    for: 'Para estudios de cejas y pestañas, salones, uñas y profesionales',
    title: ['Tus clientes', 'reservan <em>solos.</em>'],
    lead: 'Una página con tus servicios y tus horarios. El cliente elige servicio, día y hora, y la cita te llega por WhatsApp. Tú abres y cierras tu agenda desde tu panel.',
    wa: 'Hola Zerufy Studio, tengo un negocio de servicios y quiero mi página de citas.',
    hero: { phone: 'ibrows-scroll', tall: 3506, scroll: true, label: 'I Brows · Concepto' },
    pains: [
      ['Contestar “¿tienes hora hoy?” todo el día', 'El cliente ve tus horarios libres y elige.'],
      ['Mandar la lista de precios cada vez', 'Tus servicios, precios y duración en tu página.'],
      ['Citas anotadas en la cabeza o en notas', 'Cada cita te llega escrita, con servicio, día y hora.'],
      ['Clientes que no pueden reservar de noche', 'Tu página sigue agendando mientras duermes.'],
    ],
    gives: [
      'Una página con tus servicios, precios y duración',
      'El cliente elige servicio, día y hora',
      'La cita te llega por WhatsApp, lista para confirmar',
      'Fotos de tu trabajo, ubicación y redes',
      'Tu panel de administración para manejar servicios y horarios',
    ],
    demo: {
      brand: 'Tu estudio',
      icon: 'calendar',
      off: 'Cerrado',
      items: [
        { n: 'Cejas con hilo', m: '25 min', p: '$35' },
        { n: 'Lash lift', m: '60 min', p: '$110' },
        { n: 'Domingo', m: 'Horario', p: '10 am – 4 pm' },
      ],
      add: { n: 'Brow lamination', m: '50 min', p: '$100' },
      steps: [
        { a: 'price', i: 0, to: '$38', cap: 'Cambias un precio' },
        { a: 'off', i: 2, cap: 'Cierras un día' },
        { a: 'add', cap: 'Agregas un servicio' },
      ],
    },
    how: [
      { t: 'Tu cliente entra a tu link', d: 'Desde tu bio, un QR o WhatsApp.' },
      { t: 'Elige servicio, día y hora', d: 'Solo ve los horarios que tú abriste.' },
      { t: 'Te llega la cita', d: 'Por WhatsApp, con todo escrito.' },
      { t: 'Tú la confirmas', d: 'Y atiendes como siempre.' },
    ],
    control: ['Servicios y precios', 'Horarios', 'Días libres', 'Fotos de tu trabajo'],
    examples: ['ibrows'],
    faq: [
      { q: '¿Mis clientes tienen que descargar algo?', a: 'No. Abren tu link y reservan desde el navegador del celular.' },
      { q: '¿Puedo cerrar un día o cambiar mis horarios?', a: 'Sí. Desde tu panel abres y cierras días y horas cuando quieras.' },
      { q: '¿Cobra depósitos?', a: 'No. La cita te llega por WhatsApp y el cobro lo manejas tú.' },
      { q: '¿Y si algo deja de funcionar?', a: 'Nos escribes y lo arreglamos. El soporte y el mantenimiento van incluidos en la mensualidad.' },
    ],
    close: { q: '¿Tu negocio trabaja con citas?', t: 'Que tu agenda se llene <em>sola.</em>' },
  },
];

// Lo que queda de nuestro lado en todos los negocios
export const studioSide = ['Diseño con tu marca', 'Hosting y seguridad', 'Dominio conectado', 'Soporte y mantenimiento'];
